/*
 * generated by Xtext
 */
package fr.inria.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.lang.ui.internal.LuaConfigFileActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LuaConfigFileExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LuaConfigFileActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LuaConfigFileActivator.getInstance().getInjector(LuaConfigFileActivator.FR_INRIA_LANG_LUACONFIGFILE);
	}
	
}
