/*
 * generated by Xtext
 */
package fr.inria.lang.ui.contentassist

import fr.inria.lang.ui.contentassist.AbstractLuaConfigFileProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LuaConfigFileProposalProvider extends AbstractLuaConfigFileProposalProvider {
}
