/*
 * generated by Xtext
 */
package fr.inria.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LuaConfigFileUiModule extends fr.inria.lang.ui.AbstractLuaConfigFileUiModule {
	public LuaConfigFileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
