/*
* generated by Xtext
*/
package fr.inria.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LuaConfigFileStandaloneSetup extends LuaConfigFileStandaloneSetupGenerated{

	public static void doSetup() {
		new LuaConfigFileStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

