/*
 * generated by Xtext
 */
package fr.inria.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LuaConfigFileRuntimeModule extends fr.inria.lang.AbstractLuaConfigFileRuntimeModule {

}
