/*
 * generated by Xtext
 */
package fr.inria.lang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLuaConfigFileValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(fr.inria.lang.conf.ConfPackage.eINSTANCE);
		return result;
	}
}
